"""Helpers for fetching YouTube metadata, search candidates, and transcripts."""

from __future__ import annotations

import importlib.util
import json
import os
import re
import shutil
import subprocess
import sys
import threading
import wave
from dataclasses import dataclass
from html import unescape
from pathlib import Path
from urllib.parse import parse_qs, urlencode, urlparse, urlunparse

import requests

from utils.data_utils import clean_text

os.environ.setdefault("TRANSFORMERS_NO_TORCHAUDIO", "1")

YOUTUBE_VIDEOS_API = "https://www.googleapis.com/youtube/v3/videos"
YOUTUBE_SEARCH_API = "https://www.googleapis.com/youtube/v3/search"
YOUTUBE_OEMBED_API = "https://www.youtube.com/oembed"
YOUTUBE_WATCH_URL = "https://www.youtube.com/watch"
PREFERRED_TRANSCRIPT_LANGUAGES = ("si", "en", "en-US", "en-GB")
BASE_DIR = Path(__file__).resolve().parent.parent
AUDIO_CACHE_DIR = BASE_DIR / "instance" / "youtube_audio"
WHISPER_FINE_TUNED_DIR = BASE_DIR / "outputs" / "whisper_sinhala"
XLSR_SINHALA_MODEL = "janiduchamika/wav2vec2-xls-r-300m-sinhala-general-185k"
XLSR_TRANSCRIBE_SCRIPT = BASE_DIR / "tools" / "transcribe_xlsr_audio.py"
WHISPER_RUNTIME = os.environ.get("WHISPER_RUNTIME", "faster_whisper").strip().lower()
WHISPER_MODEL_NAME = os.environ.get("WHISPER_MODEL", "")
MAX_AUDIO_TRANSCRIPT_SECONDS = int(os.environ.get("MAX_AUDIO_TRANSCRIPT_SECONDS", "900"))
YOUTUBE_HEADERS = {
    "Accept-Language": "si,en-US;q=0.9,en;q=0.8",
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0 Safari/537.36"
    ),
}
ANSI_ESCAPE_RE = re.compile(r"\x1b\[[0-9;]*m")
_XLSR_MODEL_CACHE: dict[tuple[str, str, bool], tuple[object, object]] = {}
_FASTER_WHISPER_MODEL_CACHE: dict[tuple[str, str, str], object] = {}
_HUGGINGFACE_WHISPER_CACHE: dict[tuple[str, int], object] = {}
_OPENAI_WHISPER_MODEL_CACHE: dict[str, object] = {}
_MODEL_CACHE_LOCK = threading.Lock()


@dataclass(frozen=True)
class YouTubeMetadata:
    """Metadata fetched from YouTube or supplied by the browser extension."""

    video_id: str
    title: str = ""
    description: str = ""
    thumbnail_url: str = ""
    transcript: str = ""
    source: str = "extension"
    warnings: tuple[str, ...] = ()


@dataclass(frozen=True)
class WhisperTranscriptResult:
    """Transcript generated by an explicit Whisper request."""

    video_id: str
    transcript: str = ""
    source: str = "whisper"
    warnings: tuple[str, ...] = ()
    audio_duration_seconds: int = 0
    model_name: str = ""
    runtime: str = ""
    audio_path: str = ""

    def as_dict(self) -> dict:
        return {
            "video_id": self.video_id,
            "transcript": self.transcript,
            "source": self.source,
            "warnings": list(self.warnings),
            "audio_duration_seconds": self.audio_duration_seconds,
            "model_name": self.model_name,
            "runtime": self.runtime,
            "audio_path": self.audio_path,
        }


@dataclass(frozen=True)
class YouTubeSearchCandidate:
    """A YouTube search result that can become a labeling candidate."""

    video_id: str
    url: str
    title: str = ""
    description: str = ""
    channel_title: str = ""
    published_at: str = ""
    thumbnail_url: str = ""

    def as_dict(self) -> dict:
        return {
            "video_id": self.video_id,
            "url": self.url,
            "title": self.title,
            "description": self.description,
            "channel_title": self.channel_title,
            "published_at": self.published_at,
            "thumbnail_url": self.thumbnail_url,
        }


def extract_video_id(value: str) -> str:
    """Extract a YouTube video id from a URL or return a cleaned id-like string."""

    value = clean_text(value)
    if not value:
        return ""

    parsed = urlparse(value)
    if parsed.netloc:
        if parsed.netloc.endswith("youtu.be"):
            return parsed.path.strip("/")
        if "youtube.com" in parsed.netloc:
            query_id = parse_qs(parsed.query).get("v", [""])[0]
            if query_id:
                return query_id
            match = re.search(r"/(?:shorts|embed)/([^/?#]+)", parsed.path)
            if match:
                return match.group(1)

    match = re.search(r"^[A-Za-z0-9_-]{6,}$", value)
    return match.group(0) if match else ""


def search_youtube_videos(
    query: str,
    api_key: str | None = None,
    max_results: int = 10,
    page_token: str = "",
    region_code: str = "LK",
    relevance_language: str = "si",
    video_caption: str = "",
) -> tuple[list[YouTubeSearchCandidate], dict[str, str | int]]:
    """Search YouTube Data API v3 for video candidates to label."""

    query = clean_text(query)
    api_key = api_key or os.environ.get("YOUTUBE_API_KEY", "")
    if not api_key:
        raise ValueError("YOUTUBE_API_KEY is required to search YouTube candidate videos.")
    if not query:
        raise ValueError("Search query is required.")

    max_results = max(1, min(int(max_results or 10), 50))
    params = {
        "part": "snippet",
        "type": "video",
        "q": query,
        "maxResults": max_results,
        "key": api_key,
        "order": "relevance",
        "safeSearch": "none",
        "regionCode": region_code,
        "relevanceLanguage": relevance_language,
    }
    if video_caption:
        if video_caption not in {"any", "closedCaption", "none"}:
            raise ValueError("video_caption must be one of: any, closedCaption, none.")
        params["videoCaption"] = video_caption
    if page_token:
        params["pageToken"] = page_token

    try:
        response = requests.get(YOUTUBE_SEARCH_API, params=params, timeout=15)
    except requests.RequestException as exc:
        raise RuntimeError(
            "Could not reach Google YouTube Data API. Check internet connection, DNS, VPN/proxy, "
            "firewall, or try again later."
        ) from exc
    response.raise_for_status()
    payload = response.json()
    candidates: list[YouTubeSearchCandidate] = []
    for item in payload.get("items", []):
        video_id = clean_text((item.get("id") or {}).get("videoId", ""))
        snippet = item.get("snippet", {}) or {}
        if not video_id:
            continue
        thumbnails = snippet.get("thumbnails", {}) or {}
        thumbnail_url = ""
        for quality in ("high", "medium", "default"):
            if thumbnails.get(quality, {}).get("url"):
                thumbnail_url = clean_text(thumbnails[quality]["url"])
                break
        candidates.append(
            YouTubeSearchCandidate(
                video_id=video_id,
                url=f"https://www.youtube.com/watch?v={video_id}",
                title=clean_text(snippet.get("title", "")),
                description=clean_text(snippet.get("description", "")),
                channel_title=clean_text(snippet.get("channelTitle", "")),
                published_at=clean_text(snippet.get("publishedAt", "")),
                thumbnail_url=thumbnail_url,
            )
        )

    meta = {
        "next_page_token": clean_text(payload.get("nextPageToken", "")),
        "prev_page_token": clean_text(payload.get("prevPageToken", "")),
        "total_results": int((payload.get("pageInfo") or {}).get("totalResults") or 0),
        "results_per_page": int((payload.get("pageInfo") or {}).get("resultsPerPage") or len(candidates)),
    }
    return candidates, meta


def configured_whisper_runtime() -> str:
    runtime = os.environ.get("WHISPER_RUNTIME", WHISPER_RUNTIME).strip().lower()
    aliases = {
        "hf": "huggingface",
        "transformers": "huggingface",
        "openai": "openai_whisper",
        "openai-whisper": "openai_whisper",
        "faster": "faster_whisper",
        "faster-whisper": "faster_whisper",
        "xlsr": "xlsr_sinhala",
        "xls-r": "xlsr_sinhala",
        "wav2vec": "xlsr_sinhala",
        "wav2vec2": "xlsr_sinhala",
        "sinhala_xlsr": "xlsr_sinhala",
    }
    return aliases.get(runtime, runtime)


def configured_whisper_model(runtime: str | None = None) -> str:
    model_name = os.environ.get("WHISPER_MODEL", WHISPER_MODEL_NAME).strip()
    if model_name:
        return model_name
    runtime = runtime or configured_whisper_runtime()
    if runtime in {"huggingface", "faster_whisper"} and WHISPER_FINE_TUNED_DIR.exists():
        return str(WHISPER_FINE_TUNED_DIR)
    if runtime == "faster_whisper":
        return "base"
    if runtime == "openai_whisper":
        return "small"
    if runtime == "xlsr_sinhala":
        return XLSR_SINHALA_MODEL
    return "openai/whisper-small"


def configured_faster_whisper_device() -> str:
    """Use safe int8 CPU inference unless CUDA or auto selection is explicitly requested."""

    configured = clean_text(os.environ.get("WHISPER_DEVICE", "cpu")).lower() or "cpu"
    if configured != "auto":
        return configured
    try:
        import ctranslate2  # type: ignore

        return "cuda" if ctranslate2.get_cuda_device_count() > 0 else "cpu"
    except Exception:
        return "cpu"


def configured_faster_whisper_compute_type(device: str | None = None) -> str:
    configured = clean_text(os.environ.get("WHISPER_COMPUTE_TYPE", "")).lower()
    if configured:
        return configured
    return "float16" if (device or configured_faster_whisper_device()) == "cuda" else "int8"


def configured_whisper_beam_size() -> int:
    try:
        return max(1, int(os.environ.get("WHISPER_BEAM_SIZE", "5")))
    except ValueError:
        return 5


def transcript_cache_path(video_id: str) -> Path:
    return AUDIO_CACHE_DIR / f"{video_id}.transcript.txt"


def read_cached_transcript(video_id: str) -> str:
    path = transcript_cache_path(video_id)
    if path.exists():
        return clean_text(path.read_text(encoding="utf-8"))
    return ""


def write_cached_transcript(video_id: str, transcript: str) -> None:
    transcript = clean_text(transcript)
    if not transcript:
        return
    AUDIO_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    transcript_cache_path(video_id).write_text(transcript, encoding="utf-8")


def fetch_youtube_metadata(
    video_id: str,
    api_key: str | None = None,
    use_audio_fallback: bool = True,
    transcript_languages: tuple[str, ...] | None = None,
    allow_transcript_language_fallback: bool = True,
) -> YouTubeMetadata:
    """Fetch title, description, thumbnail, and transcript for a YouTube video."""

    api_key = api_key or os.environ.get("YOUTUBE_API_KEY", "")
    video_id = extract_video_id(video_id)
    if not video_id:
        return YouTubeMetadata(video_id="", warnings=("Missing or invalid YouTube video id.",))

    transcript, transcript_warnings = fetch_youtube_transcript(
        video_id,
        languages=transcript_languages,
        allow_language_fallback=allow_transcript_language_fallback,
    )
    if not transcript and use_audio_fallback:
        audio_transcript, audio_warnings = fetch_audio_transcript(video_id)
        transcript = audio_transcript
        transcript_warnings = audio_warnings if audio_transcript else (*transcript_warnings, *audio_warnings)
    elif not transcript and not use_audio_fallback:
        transcript_warnings = (
            *transcript_warnings,
            "Audio transcript fallback is disabled for YouTube Data API v3 test loading.",
        )

    if not api_key:
        fallback = fetch_youtube_page_metadata(video_id)
        warnings = [
            "YOUTUBE_API_KEY is not set; using public YouTube page metadata where available.",
            *fallback.warnings,
            *transcript_warnings,
        ]
        return YouTubeMetadata(
            video_id=video_id,
            title=fallback.title,
            description=fallback.description,
            thumbnail_url=fallback.thumbnail_url,
            transcript=transcript,
            source="youtube_page",
            warnings=tuple(warnings),
        )

    response = requests.get(
        YOUTUBE_VIDEOS_API,
        params={"part": "snippet", "id": video_id, "key": api_key},
        timeout=15,
    )
    response.raise_for_status()
    payload = response.json()
    items = payload.get("items", [])
    if not items:
        return YouTubeMetadata(video_id=video_id, warnings=("YouTube API returned no video item.",))

    snippet = items[0].get("snippet", {})
    thumbnails = snippet.get("thumbnails", {})
    thumbnail_url = ""
    for quality in ("maxres", "standard", "high", "medium", "default"):
        if thumbnails.get(quality, {}).get("url"):
            thumbnail_url = clean_text(thumbnails[quality]["url"])
            break

    return YouTubeMetadata(
        video_id=video_id,
        title=clean_text(snippet.get("title", "")),
        description=clean_text(snippet.get("description", "")),
        thumbnail_url=thumbnail_url,
        transcript=transcript,
        source="youtube_api",
        warnings=transcript_warnings,
    )


def fetch_youtube_page_metadata(video_id: str) -> YouTubeMetadata:
    """Best-effort title, description, and thumbnail fallback without a Data API key."""

    video_id = extract_video_id(video_id)
    if not video_id:
        return YouTubeMetadata(video_id="", warnings=("Missing or invalid YouTube video id.",))

    title = ""
    description = ""
    thumbnail_url = f"https://i.ytimg.com/vi/{video_id}/hqdefault.jpg"
    warnings: list[str] = []

    try:
        response = requests.get(
            YOUTUBE_OEMBED_API,
            params={"url": f"https://www.youtube.com/watch?v={video_id}", "format": "json"},
            headers=YOUTUBE_HEADERS,
            timeout=10,
        )
        if response.ok:
            payload = response.json()
            title = clean_text(payload.get("title", ""))
            thumbnail_url = clean_text(payload.get("thumbnail_url", "")) or thumbnail_url
    except requests.RequestException:
        warnings.append("Could not fetch public YouTube oEmbed metadata.")

    try:
        response = requests.get(
            YOUTUBE_WATCH_URL,
            params={"v": video_id},
            headers=YOUTUBE_HEADERS,
            timeout=15,
        )
        if response.ok:
            html = response.text
            title = title or extract_meta_content(html, "title")
            description = extract_meta_content(html, "description")
            thumbnail_url = extract_meta_content(html, "image") or thumbnail_url
        else:
            warnings.append("Could not fetch the YouTube watch page metadata.")
    except requests.RequestException:
        warnings.append("Could not fetch the YouTube watch page metadata.")

    return YouTubeMetadata(
        video_id=video_id,
        title=title,
        description=description,
        thumbnail_url=thumbnail_url,
        source="youtube_page",
        warnings=tuple(warnings),
    )


def fetch_youtube_transcript(
    video_id: str,
    languages: tuple[str, ...] | None = None,
    allow_language_fallback: bool = True,
) -> tuple[str, tuple[str, ...]]:
    """Fetch captions/transcript for a YouTube video when captions are publicly available."""

    video_id = extract_video_id(video_id)
    if not video_id:
        return "", ("Missing or invalid YouTube video id.",)

    use_shared_cache = languages is None and allow_language_fallback
    if use_shared_cache:
        cached = read_cached_transcript(video_id)
        if cached:
            return cached, ()

    languages = languages or PREFERRED_TRANSCRIPT_LANGUAGES
    transcript = fetch_transcript_with_package(
        video_id,
        languages=languages,
        allow_language_fallback=allow_language_fallback,
    )
    if transcript:
        if use_shared_cache:
            write_cached_transcript(video_id, transcript)
        return transcript, ()

    try:
        response = requests.get(
            YOUTUBE_WATCH_URL,
            params={"v": video_id},
            headers=YOUTUBE_HEADERS,
            timeout=15,
        )
        response.raise_for_status()
        caption_tracks = parse_caption_tracks(response.text)
        transcript = fetch_transcript_from_caption_tracks(
            caption_tracks,
            languages=languages,
            allow_language_fallback=allow_language_fallback,
        )
        if transcript:
            if use_shared_cache:
                write_cached_transcript(video_id, transcript)
            return transcript, ()
    except (requests.RequestException, ValueError, json.JSONDecodeError):
        pass

    language_text = ", ".join(languages)
    return "", (f"Transcript was not available from public YouTube captions for languages: {language_text}.",)


def fetch_audio_transcript(video_id: str) -> tuple[str, tuple[str, ...]]:
    """Download audio and transcribe it with a local Whisper-compatible model."""

    result = generate_whisper_transcript(video_id, force_refresh=False)
    return result.transcript, result.warnings


def generate_whisper_transcript(video_id: str, force_refresh: bool = False) -> WhisperTranscriptResult:
    """Explicitly download YouTube audio and transcribe it with the configured Whisper runtime."""

    video_id = extract_video_id(video_id)
    runtime = configured_whisper_runtime()
    model_name = configured_whisper_model(runtime)
    if not video_id:
        return WhisperTranscriptResult(
            video_id="",
            warnings=("Missing or invalid YouTube video id.",),
            runtime=runtime,
            model_name=model_name,
        )

    cached = "" if force_refresh else read_cached_transcript(video_id)
    if cached:
        audio_path = cached_youtube_audio(video_id)
        return WhisperTranscriptResult(
            video_id=video_id,
            transcript=cached,
            warnings=("Transcript loaded from local cache.",),
            audio_duration_seconds=audio_duration_seconds(audio_path) if audio_path else 0,
            model_name=model_name,
            runtime=runtime,
            audio_path=str(audio_path) if audio_path else "",
        )

    status = audio_transcript_status()
    if not status["ffmpeg"]:
        return WhisperTranscriptResult(
            video_id=video_id,
            warnings=("Audio transcript generation needs ffmpeg on PATH.",),
            model_name=model_name,
            runtime=runtime,
        )
    if not status["yt_dlp"]:
        return WhisperTranscriptResult(
            video_id=video_id,
            warnings=("Audio transcript generation needs yt-dlp installed.",),
            model_name=model_name,
            runtime=runtime,
        )
    if not status["whisper_backend"]:
        warning = (
            "Audio transcript generation needs faster-whisper, Hugging Face Whisper dependencies, "
            "or a working openai-whisper install. YouTube Data API metadata can still be used without audio transcription."
        )
        if status.get("openai_whisper_error"):
            warning = f"{warning} OpenAI Whisper is currently unavailable: {status['openai_whisper_error']}"
        return WhisperTranscriptResult(video_id=video_id, warnings=(warning,), model_name=model_name, runtime=runtime)

    # All supported ASR runtimes can decode the downloaded m4a/webm stream.
    # Skipping the intermediate WAV removes a full-file conversion and large write.
    audio_path, download_warnings = download_youtube_audio(video_id, convert_to_wav=False)
    if not audio_path:
        return WhisperTranscriptResult(video_id=video_id, warnings=download_warnings, model_name=model_name, runtime=runtime)

    transcript, whisper_warnings = transcribe_audio_with_whisper(audio_path)
    duration = audio_duration_seconds(audio_path)
    if transcript:
        write_cached_transcript(video_id, transcript)
        return WhisperTranscriptResult(
            video_id=video_id,
            transcript=transcript,
            warnings=("Transcript was generated from downloaded audio with Whisper.", *whisper_warnings),
            audio_duration_seconds=duration,
            model_name=model_name,
            runtime=runtime,
            audio_path=str(audio_path),
        )
    return WhisperTranscriptResult(
        video_id=video_id,
        warnings=whisper_warnings,
        audio_duration_seconds=duration,
        model_name=model_name,
        runtime=runtime,
        audio_path=str(audio_path),
    )


def download_youtube_audio(
    video_id: str,
    max_duration_seconds: int | None = MAX_AUDIO_TRANSCRIPT_SECONDS,
    context: str = "Audio transcript fallback",
    convert_to_wav: bool = True,
) -> tuple[Path | None, tuple[str, ...]]:
    """Download audio and optionally convert it to 16 kHz mono WAV."""

    try:
        from yt_dlp import YoutubeDL  # type: ignore
    except ImportError:
        return None, (f"{context} needs yt-dlp installed.",)

    AUDIO_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    url = f"https://www.youtube.com/watch?v={video_id}"
    output_template = str(AUDIO_CACHE_DIR / f"{video_id}.%(ext)s")
    wav_path = AUDIO_CACHE_DIR / f"{video_id}.wav"

    cached_audio = cached_youtube_audio(video_id)
    if cached_audio:
        if cached_audio.suffix.lower() == ".wav" or not convert_to_wav:
            return cached_audio, ()
        warning = convert_audio_to_wav(cached_audio, wav_path, max_duration_seconds=max_duration_seconds, context=context)
        return (None, (warning,)) if warning else (wav_path, ())

    downloaded_info = None
    warnings: list[str] = []
    for options in ytdlp_download_option_sets(output_template):
        try:
            options = dict(options)
            if max_duration_seconds is not None:
                options["match_filter"] = ytdlp_duration_filter(max_duration_seconds, context)
            with YoutubeDL(options) as ydl:
                downloaded_info = ydl.extract_info(url, download=True)
                break
        except Exception as exc:  # noqa: BLE001 - yt-dlp raises broad extractor/download exceptions.
            detail = strip_terminal_codes(str(exc))
            warnings.append(detail)
            if "skipped videos longer than" in detail:
                return None, (detail[detail.find(context) :] if context in detail else detail,)
            continue
    if downloaded_info is None:
        detail = " ".join(warnings[-2:]) if warnings else "unknown yt-dlp error"
        if "403" in detail or "Forbidden" in detail:
            detail = (
                f"{detail} YouTube blocked this download. Try setting YTDLP_COOKIES_BROWSER=chrome "
                "or YTDLP_COOKIES_FILE to an exported cookies.txt, then restart the app."
            )
        return None, (f"{context} could not download audio: {detail}",)

    source_path = downloaded_audio_path(video_id, downloaded_info)
    if not source_path:
        return None, (f"{context} downloaded no usable audio file.",)

    if source_path.suffix.lower() == ".wav" and audio_duration_seconds(source_path) > 0:
        return source_path, ()
    if not convert_to_wav:
        return source_path, ()

    warning = convert_audio_to_wav(source_path, wav_path, max_duration_seconds=max_duration_seconds, context=context)
    if warning:
        return None, (warning,)
    return wav_path, ()


def ytdlp_duration_filter(max_duration_seconds: int, context: str):
    """Reject overlong videos before yt-dlp starts downloading their audio."""

    def reject_overlong_video(info: dict, *, incomplete: bool = False) -> str | None:
        duration = int(info.get("duration") or 0)
        if not incomplete and duration > max_duration_seconds:
            minutes = max_duration_seconds // 60
            return f"{context} skipped videos longer than {minutes} minutes."
        return None

    return reject_overlong_video


def ytdlp_download_option_sets(output_template: str) -> list[dict]:
    """Return yt-dlp option fallbacks for YouTube 403/client blocking cases."""

    base_options = {
        "format": "bestaudio[ext=m4a][protocol^=http]/bestaudio[protocol^=http]/bestaudio/best",
        "noplaylist": True,
        "outtmpl": output_template,
        "quiet": True,
        "no_warnings": True,
        "socket_timeout": 30,
        "retries": 3,
        "fragment_retries": 3,
        "extractor_retries": 3,
        "file_access_retries": 3,
        "overwrites": True,
        "http_headers": YOUTUBE_HEADERS,
        "extractor_args": {"youtube": {"player_client": ["android", "web"]}},
    }
    option_sets = [base_options]
    option_sets.append({**base_options, "extractor_args": {"youtube": {"player_client": ["web_safari", "mweb", "android"]}}})

    cookies_file = clean_text(os.environ.get("YTDLP_COOKIES_FILE", ""))
    if cookies_file:
        option_sets.append({**base_options, "cookiefile": cookies_file})

    cookies_browser = clean_text(os.environ.get("YTDLP_COOKIES_BROWSER", ""))
    if cookies_browser:
        browser_parts = [part.strip() for part in cookies_browser.split(":") if part.strip()]
        option_sets.append({**base_options, "cookiesfrombrowser": tuple(browser_parts)})

    return option_sets


def cached_youtube_audio(video_id: str) -> Path | None:
    wav_path = AUDIO_CACHE_DIR / f"{video_id}.wav"
    if wav_path.exists() and audio_duration_seconds(wav_path) > 0:
        return wav_path
    for path in sorted(AUDIO_CACHE_DIR.glob(f"{video_id}.*"), key=lambda item: item.stat().st_mtime, reverse=True):
        if path.suffix.lower() in {".m4a", ".webm", ".mp3", ".opus"} and audio_duration_seconds(path) > 0:
            return path
    return None


def downloaded_audio_path(video_id: str, info: dict | None = None) -> Path | None:
    """Find the actual audio file yt-dlp produced."""

    candidates: list[Path] = []
    for download in (info or {}).get("requested_downloads", []) or []:
        filepath = clean_text(download.get("filepath") or download.get("filename") or "")
        if filepath:
            candidates.append(Path(filepath))
    filepath = clean_text((info or {}).get("filepath") or (info or {}).get("_filename") or "")
    if filepath:
        candidates.append(Path(filepath))
    candidates.extend(sorted(AUDIO_CACHE_DIR.glob(f"{video_id}.*"), key=lambda path: path.stat().st_mtime, reverse=True))

    ignored_suffixes = {".part", ".ytdl", ".txt"}
    for path in candidates:
        if path.exists() and path.suffix.lower() not in ignored_suffixes and ".transcript" not in path.name:
            return path
    return None


def convert_audio_to_wav(
    source_path: Path,
    wav_path: Path,
    max_duration_seconds: int | None = MAX_AUDIO_TRANSCRIPT_SECONDS,
    context: str = "Audio transcript fallback",
) -> str:
    """Convert downloaded audio to 16 kHz mono WAV for Whisper."""

    if not shutil.which("ffmpeg"):
        return f"{context} needs ffmpeg on PATH."
    try:
        wav_path.parent.mkdir(parents=True, exist_ok=True)
        result = subprocess.run(
            [
                "ffmpeg",
                "-y",
                "-i",
                str(source_path),
                "-vn",
                "-ac",
                "1",
                "-ar",
                "16000",
                "-f",
                "wav",
                str(wav_path),
            ],
            check=False,
            capture_output=True,
            text=True,
            timeout=max_duration_seconds + 120 if max_duration_seconds is not None else None,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return f"{context} could not convert audio with ffmpeg: {exc}"

    if result.returncode != 0:
        detail = strip_terminal_codes(result.stderr or result.stdout or "Conversion failed.")
        return f"{context} could not convert audio with ffmpeg: {detail[-700:]}"
    if not wav_path.exists() or audio_duration_seconds(wav_path) <= 0:
        return f"{context} converted audio, but the WAV file was not readable."
    return ""


def audio_duration_seconds(audio_path: Path) -> int:
    """Return audio duration when available."""

    if not audio_path.exists():
        return 0
    ffprobe_duration = valid_audio_duration_seconds(audio_path)
    if ffprobe_duration > 0:
        return int(ffprobe_duration)
    try:
        with wave.open(str(audio_path), "rb") as audio:
            frames = audio.getnframes()
            rate = audio.getframerate()
            return int(frames / rate) if rate else 0
    except (wave.Error, OSError):
        return 0


def valid_audio_duration_seconds(audio_path: Path) -> float:
    """Return duration through ffprobe for any ffmpeg-readable audio file."""

    if not shutil.which("ffprobe"):
        return 0.0
    try:
        result = subprocess.run(
            [
                "ffprobe",
                "-v",
                "error",
                "-show_entries",
                "format=duration",
                "-of",
                "default=noprint_wrappers=1:nokey=1",
                str(audio_path),
            ],
            check=False,
            capture_output=True,
            text=True,
            timeout=20,
        )
    except (OSError, subprocess.SubprocessError, ValueError):
        return 0.0
    if result.returncode != 0:
        return 0.0
    try:
        return float((result.stdout or "").strip())
    except ValueError:
        return 0.0


def strip_terminal_codes(value: str) -> str:
    return clean_text(ANSI_ESCAPE_RE.sub("", value))


def audio_transcript_status() -> dict[str, bool | str | int]:
    """Return dependency status for the audio-to-Whisper transcript fallback."""

    runtime = configured_whisper_runtime()
    faster_whisper = importlib.util.find_spec("faster_whisper") is not None
    openai_whisper, openai_whisper_error = openai_whisper_status()
    huggingface_whisper = huggingface_whisper_available()
    xlsr_sinhala = xlsr_sinhala_available()
    runtime_available = {
        "faster_whisper": faster_whisper,
        "openai_whisper": openai_whisper,
        "huggingface": huggingface_whisper,
        "xlsr_sinhala": xlsr_sinhala,
    }.get(runtime, False)
    return {
        "ffmpeg": shutil.which("ffmpeg") is not None,
        "yt_dlp": importlib.util.find_spec("yt_dlp") is not None,
        "faster_whisper": faster_whisper,
        "huggingface": huggingface_whisper,
        "openai_whisper": openai_whisper,
        "xlsr_sinhala": xlsr_sinhala,
        "whisper_backend": runtime_available,
        "runtime": runtime,
        "model": configured_whisper_model(runtime),
        "device": configured_faster_whisper_device() if runtime == "faster_whisper" else "runtime_default",
        "compute_type": (
            configured_faster_whisper_compute_type() if runtime == "faster_whisper" else "runtime_default"
        ),
        "beam_size": configured_whisper_beam_size(),
        "openai_whisper_error": openai_whisper_error,
    }


def openai_whisper_available() -> bool:
    available, _ = openai_whisper_status()
    return available


def openai_whisper_status() -> tuple[bool, str]:
    """Detect OpenAI Whisper without crashing on broken torchaudio installs."""

    try:
        import whisper  # type: ignore
    except Exception as exc:  # noqa: BLE001 - torchaudio can raise OSError at import time.
        return False, str(exc)
    return hasattr(whisper, "load_model"), ""


def huggingface_whisper_available() -> bool:
    return importlib.util.find_spec("transformers") is not None and importlib.util.find_spec("torch") is not None


def xlsr_sinhala_available() -> bool:
    native_available = importlib.util.find_spec("transformers") is not None and importlib.util.find_spec("torch") is not None
    return native_available or bool(xlsr_python_executable())


def transcribe_audio_with_whisper(audio_path: Path) -> tuple[str, tuple[str, ...]]:
    """Transcribe an audio file with the configured Whisper runtime."""

    runtime = configured_whisper_runtime()
    if runtime == "xlsr_sinhala":
        transcript = transcribe_audio_with_xlsr_sinhala(audio_path)
    elif runtime == "huggingface":
        transcript = transcribe_audio_with_huggingface_whisper(audio_path)
    elif runtime == "openai_whisper":
        transcript = transcribe_audio_with_openai_whisper(audio_path)
    else:
        transcript = transcribe_audio_with_faster_whisper(audio_path)

    if transcript:
        return transcript, ()
    return "", (f"Whisper runtime '{runtime}' did not produce a transcript.",)


def transcribe_audio_with_huggingface_whisper(audio_path: Path) -> str:
    try:
        import torch
        from transformers import pipeline
    except Exception:
        return ""

    try:
        device = 0 if torch.cuda.is_available() else -1
        model_name = configured_whisper_model("huggingface")
        cache_key = (model_name, device)
        with _MODEL_CACHE_LOCK:
            transcriber = _HUGGINGFACE_WHISPER_CACHE.get(cache_key)
            if transcriber is None:
                transcriber = pipeline(
                    "automatic-speech-recognition",
                    model=model_name,
                    device=device,
                )
                _HUGGINGFACE_WHISPER_CACHE[cache_key] = transcriber
        result = transcriber(str(audio_path), generate_kwargs={"language": "sinhalese", "task": "transcribe"})
        if isinstance(result, dict):
            return clean_text(result.get("text", ""))
        return clean_text(result)
    except Exception:
        return ""


def transcribe_audio_with_xlsr_sinhala(audio_path: Path) -> str:
    """Transcribe Sinhala audio with the janiduchamika XLS-R CTC model."""

    try:
        import numpy as np
        import torch
        from transformers import AutoModelForCTC, AutoProcessor
    except Exception:
        return transcribe_audio_with_xlsr_subprocess(audio_path)

    try:
        audio = decode_audio_array_16k(audio_path, np)
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        model_name = configured_whisper_model("xlsr_sinhala")
        use_fp16 = os.environ.get("XLSR_FP16", "").strip().lower() in {"1", "true", "yes"}
        cache_key = (model_name, str(device), use_fp16)
        if cache_key not in _XLSR_MODEL_CACHE:
            processor = AutoProcessor.from_pretrained(model_name)
            model = AutoModelForCTC.from_pretrained(model_name)
            model.to(device)
            if device.type == "cuda" and use_fp16:
                model.half()
            model.eval()
            _XLSR_MODEL_CACHE[cache_key] = (processor, model)
        processor, model = _XLSR_MODEL_CACHE[cache_key]
        inputs = processor(audio, sampling_rate=16000, return_tensors="pt", padding=True)
        inputs = {key: value.to(device) for key, value in inputs.items()}
        with torch.no_grad():
            logits = model(**inputs).logits
        predicted_ids = torch.argmax(logits, dim=-1)
        return clean_text(processor.batch_decode(predicted_ids)[0])
    except Exception:
        return transcribe_audio_with_xlsr_subprocess(audio_path)


def transcribe_audio_with_xlsr_subprocess(audio_path: Path) -> str:
    python_executable = xlsr_python_executable()
    if not python_executable or not XLSR_TRANSCRIBE_SCRIPT.exists():
        return ""
    command = [
        python_executable,
        str(XLSR_TRANSCRIBE_SCRIPT),
        "--audio-path",
        str(audio_path.resolve()),
        "--model-name",
        configured_whisper_model("xlsr_sinhala"),
        "--local-files-only",
        "--cpu",
    ]
    try:
        result = subprocess.run(
            command,
            check=False,
            capture_output=True,
            text=True,
            encoding="utf-8",
            timeout=max(180, int(audio_duration_seconds(audio_path)) * 4),
        )
    except (OSError, subprocess.SubprocessError, ValueError):
        return ""
    if result.returncode != 0:
        return ""
    lines = [clean_text(line) for line in (result.stdout or "").splitlines() if clean_text(line)]
    return lines[-1] if lines else ""


def xlsr_python_executable() -> str:
    configured = clean_text(os.environ.get("XLSR_PYTHON", ""))
    candidates = [
        configured,
        str(Path.home() / "AppData" / "Local" / "Programs" / "Python" / "Python311" / "python.exe"),
        shutil.which("python") or "",
        sys.executable,
    ]
    for candidate in candidates:
        if candidate and Path(candidate).exists():
            return candidate
    return ""


def decode_audio_array_16k(audio_path: Path, np_module) -> object:
    result = subprocess.run(
        [
            "ffmpeg",
            "-nostdin",
            "-hide_banner",
            "-loglevel",
            "error",
            "-i",
            str(audio_path),
            "-ac",
            "1",
            "-ar",
            "16000",
            "-f",
            "s16le",
            "-",
        ],
        check=True,
        stdout=subprocess.PIPE,
    )
    return np_module.frombuffer(result.stdout, np_module.int16).astype(np_module.float32) / 32768.0


def transcribe_audio_with_faster_whisper(audio_path: Path) -> str:
    try:
        from faster_whisper import WhisperModel  # type: ignore
    except ImportError:
        return ""

    try:
        model_name = configured_whisper_model("faster_whisper")
        device = configured_faster_whisper_device()
        compute_type = configured_faster_whisper_compute_type(device)
        cache_key = (model_name, device, compute_type)
        with _MODEL_CACHE_LOCK:
            model = _FASTER_WHISPER_MODEL_CACHE.get(cache_key)
            if model is None:
                model_options: dict[str, int] = {}
                try:
                    cpu_threads = int(os.environ.get("WHISPER_CPU_THREADS", "0"))
                except ValueError:
                    cpu_threads = 0
                if cpu_threads > 0:
                    model_options["cpu_threads"] = cpu_threads
                model = WhisperModel(
                    model_name,
                    device=device,
                    compute_type=compute_type,
                    **model_options,
                )
                _FASTER_WHISPER_MODEL_CACHE[cache_key] = model
        beam_size = configured_whisper_beam_size()
        segments, _ = model.transcribe(
            str(audio_path),
            language="si",
            vad_filter=True,
            beam_size=beam_size,
            best_of=beam_size,
        )
        return clean_text(" ".join(clean_text(segment.text) for segment in segments))
    except Exception:
        return ""


def transcribe_audio_with_openai_whisper(audio_path: Path) -> str:
    try:
        import whisper  # type: ignore
    except Exception:
        return ""

    try:
        model_name = configured_whisper_model("openai_whisper")
        with _MODEL_CACHE_LOCK:
            model = _OPENAI_WHISPER_MODEL_CACHE.get(model_name)
            if model is None:
                model = whisper.load_model(model_name)
                _OPENAI_WHISPER_MODEL_CACHE[model_name] = model
        result = model.transcribe(str(audio_path), language="si")
        return clean_text(result.get("text", ""))
    except Exception:
        return ""


def fetch_transcript_with_package(
    video_id: str,
    languages: tuple[str, ...] | None = None,
    allow_language_fallback: bool = True,
) -> str:
    """Use youtube-transcript-api when installed; otherwise return an empty transcript."""

    try:
        from youtube_transcript_api import YouTubeTranscriptApi  # type: ignore
    except ImportError:
        return ""

    languages = languages or PREFERRED_TRANSCRIPT_LANGUAGES
    snippets = None
    try:
        if hasattr(YouTubeTranscriptApi, "get_transcript"):
            snippets = YouTubeTranscriptApi.get_transcript(video_id, languages=list(languages))
        else:
            snippets = YouTubeTranscriptApi().fetch(video_id, languages=list(languages))
    except Exception:
        try:
            transcript_list = YouTubeTranscriptApi.list_transcripts(video_id)
            transcript = None
            for language in languages:
                try:
                    transcript = transcript_list.find_transcript([language])
                    break
                except Exception:
                    continue
            if not transcript and not allow_language_fallback:
                return ""
            transcript = transcript or next(iter(transcript_list), None)
            snippets = transcript.fetch() if transcript else None
        except Exception:
            return ""

    return transcript_from_snippets(snippets or [])


def parse_caption_tracks(html: str) -> list[dict]:
    marker = '"captionTracks":'
    start = html.find(marker)
    if start == -1:
        return []
    decoder = json.JSONDecoder()
    tracks, _ = decoder.raw_decode(html[start + len(marker) :])
    return tracks if isinstance(tracks, list) else []


def fetch_transcript_from_caption_tracks(
    caption_tracks: list[dict],
    languages: tuple[str, ...] | None = None,
    allow_language_fallback: bool = True,
) -> str:
    if not caption_tracks:
        return ""
    track = preferred_caption_track(
        caption_tracks,
        languages=languages,
        allow_language_fallback=allow_language_fallback,
    )
    if not track:
        return ""
    base_url = clean_text(track.get("baseUrl", ""))
    if not base_url:
        return ""
    response = requests.get(with_query_param(unescape(base_url), "fmt", "json3"), timeout=15)
    response.raise_for_status()
    return transcript_from_json3(response.json())


def preferred_caption_track(
    caption_tracks: list[dict],
    languages: tuple[str, ...] | None = None,
    allow_language_fallback: bool = True,
) -> dict:
    languages = languages or PREFERRED_TRANSCRIPT_LANGUAGES
    for language in languages:
        for track in caption_tracks:
            if caption_track_matches_language(track, language):
                return track
    if not allow_language_fallback:
        return {}
    return caption_tracks[0]


def caption_track_matches_language(track: dict, language: str) -> bool:
    """Match exact and regional YouTube caption language variants."""

    wanted = clean_text(language).lower()
    language_code = clean_text(track.get("languageCode", "")).lower()
    if language_code == wanted or language_code.startswith(f"{wanted}-"):
        return True
    if wanted == "si":
        searchable_values = [
            language_code,
            clean_text(track.get("name", {}).get("simpleText", "") if isinstance(track.get("name"), dict) else track.get("name", "")),
            clean_text(track.get("vssId", "")),
            clean_text(track.get("kind", "")),
        ]
        for translation in track.get("translationLanguages", []) or []:
            searchable_values.append(clean_text(translation.get("languageCode", "")))
            name = translation.get("languageName", {})
            searchable_values.append(clean_text(name.get("simpleText", "") if isinstance(name, dict) else name))
        lowered = " ".join(searchable_values).lower()
        return any(marker in lowered for marker in ["sinhala", "sinhalese", "සිංහල", ".si", " si "])
    return False


def with_query_param(url: str, key: str, value: str) -> str:
    parsed = urlparse(url)
    query = parse_qs(parsed.query)
    query[key] = [value]
    return urlunparse(parsed._replace(query=urlencode(query, doseq=True)))


def transcript_from_json3(payload: dict) -> str:
    parts = []
    for event in payload.get("events", []):
        for segment in event.get("segs", []):
            text = clean_text(segment.get("utf8", ""))
            if text:
                parts.append(text)
    return clean_text(" ".join(parts))


def transcript_from_snippets(snippets) -> str:
    parts = []
    for snippet in snippets:
        text = snippet.get("text", "") if isinstance(snippet, dict) else getattr(snippet, "text", "")
        text = clean_text(text)
        if text:
            parts.append(text)
    return clean_text(" ".join(parts))


def extract_meta_content(html: str, property_name: str) -> str:
    patterns = (
        rf'<meta\s+(?:property|name)=["\']og:{re.escape(property_name)}["\']\s+content=["\']([^"\']*)',
        rf'<meta\s+content=["\']([^"\']*)["\']\s+(?:property|name)=["\']og:{re.escape(property_name)}["\']',
        rf'<meta\s+name=["\']{re.escape(property_name)}["\']\s+content=["\']([^"\']*)',
        rf'<meta\s+content=["\']([^"\']*)["\']\s+name=["\']{re.escape(property_name)}["\']',
    )
    for pattern in patterns:
        match = re.search(pattern, html, flags=re.IGNORECASE)
        if match:
            return clean_text(unescape(match.group(1)))
    return ""


def merge_metadata(
    api_metadata: YouTubeMetadata,
    page_data: dict,
    use_transcript: bool = True,
    warn_missing_transcript: bool = True,
) -> YouTubeMetadata:
    """Prefer API title/description and optional browser transcript/page fallbacks."""

    warnings = list(api_metadata.warnings)
    page_title = clean_text(page_data.get("title", ""))
    page_description = clean_text(page_data.get("description", ""))
    page_thumbnail_url = clean_text(page_data.get("thumbnail_url") or page_data.get("thumbnail", ""))
    page_transcript = clean_text(page_data.get("transcript", ""))

    title = api_metadata.title or page_title
    description = api_metadata.description or page_description
    thumbnail_url = api_metadata.thumbnail_url or page_thumbnail_url
    transcript = (api_metadata.transcript or page_transcript) if use_transcript else ""

    if use_transcript and warn_missing_transcript and not transcript:
        warnings.append("Transcript was not found. Open YouTube's transcript panel or paste transcript text for stronger predictions.")
    if not use_transcript:
        warnings.append("Transcript input is disabled for this test; prediction used title and description only.")

    return YouTubeMetadata(
        video_id=api_metadata.video_id or extract_video_id(str(page_data.get("video_id", ""))),
        title=title,
        description=description,
        thumbnail_url=thumbnail_url,
        transcript=transcript,
        source=api_metadata.source,
        warnings=tuple(warnings),
    )
